// angular-todo/src/app/listview/listview.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';
import TodoItem from '../shared/todoitem.model';

@Component({
  selector: 'app-listview',
  templateUrl: './listview.component.html',
  styleUrls: ['./listview.component.css']
})
export class ListviewComponent implements OnInit {

  @Input() title: string;
  @Input() items: TodoItem[];
  @Input() panelClass: string;
  @Input() labelClass: string;
  @Output() itemClick = new EventEmitter<TodoItem>();

  constructor() { }

  ngOnInit() {
  }

  onClick(item: TodoItem) {
    this.itemClick.emit(item);
  }

}

<div class="panel {{panelClass}}">
  <div class="panel-heading">
    <span>{{title}}<span class="badge badge-important pull-right">{{items.length}}</span></span>
  </div>
  <ul class="list-group">
    <li *ngFor="let item of items" class="list-group-item">
      <label class="{{labelClass}}">
        <input type="checkbox" (click)="onClick(item)" />
        {{item.title}}
      </label>
      <span class="text-muted pull-right">{{item.createTime.toString()}}</span>
    </li>
  </ul>
</div>

// react-todo/src/components/listview.jsx
import * as React from 'react';

const ListView = ({ title, items, panelClass, labelClass, onClick }) => {
  return (
    <div className={"panel " + panelClass}>
      <div className="panel-heading">
        <span>{title}<span className="badge badge-important pull-right">{items.length}</span></span>
      </div>
      <ul className="list-group">
        {items.map(item =>
          <li key={item.id} className="list-group-item">
            <label className={labelClass}>
              <input type="checkbox" onClick={() => onClick(item)} />
              {item.title}
            </label>
            <span className="text-muted pull-right">{item.createTime.toString()}</span>
          </li>
        )}
      </ul>
    </div>
  )
}

export default ListView;
