// angular-todo/src/app/todo/todo.component.ts
import { Component, OnInit } from '@angular/core';
import TodoItem from '../shared/todoitem.model';

@Component({
  selector: 'app-todo',
  templateUrl: './todo.component.html',
  styleUrls: ['./todo.component.css']
})
export class TodoComponent implements OnInit {

  todolist: TodoItem[] = [];
  donelist: TodoItem[] = [];
  stamp = 0;
  input = '';

  constructor() { }

  ngOnInit() {
  }

  addTodo() {
    if (this.input) {
      this.todolist.push({
        id: this.stamp,
        title: this.input,
        createTime: new Date()
      });
      this.input = '';
      this.stamp++;
    }
  }

  getDone(task) {
    const index = this.todolist.indexOf(task);
    this.todolist.splice(index, 1);
    this.donelist.push(task);
  }

  discard(task) {
    const index = this.donelist.indexOf(task);
    this.donelist.splice(index, 1);
  }

}

<div id="todo-area">
  <div class="panel input-group">
    <input class="form-control" type="text" [(ngModel)]="input" (keyup.enter)="addTodo()" />
    <span class="input-group-btn">
      <a class="btn btn-default" (click)="addTodo()">Add</a>
    </span>
  </div>
  <app-listview title="Todo List" [items]="todolist" panelClass="panel-primary" (itemClick)="getDone($event)"></app-listview>
  <app-listview title="Done List" [items]="donelist" panelClass="panel-success" labelClass="text-crossline" (itemClick)="discard($event)"></app-listview>
</div>

// react-todo/src/components/todo.jsx
import * as React from 'react';
import ListView from './listview';

class Todo extends React.Component {
  constructor(props) {
    super(props);
    this.tempData = {
      stamp: 0
    };
    this.state = {
      todolist: [],
      donelist: [],
      input: ''
    }
  }

  render() {
    const { todolist, donelist, input } = this.state;

    const handleChange = event => {
      this.setState({
        ...this.state,
        input: event.target.value
      });
    };

    const addTodo = () => {
      if (this.state.input) {
        this.setState({
          ...this.state,
          todolist: [
            ...this.state.todolist,
            {
              id: this.tempData.stamp,
              title: this.state.input,
              createTime: new Date()
            }
          ],
          input: ''
        });

        this.tempData.stamp++;
      }
    };

    const getDone = task => {
      this.setState({
        ...this.state,
        todolist: this.state.todolist.filter(item => item !== task),
        donelist: [
          ...this.state.donelist,
          task
        ]
      });
    };

    const discard = task => {
      this.setState({
        ...this.state,
        donelist: this.state.donelist.filter(item => item !== task)
      });
    };

    return (
      <div id="todo-area">
        <div className="panel input-group">
          <input className="form-control" type="text" value={input} onChange={handleChange} onKeyPress={event => event.key === 'Enter' && addTodo()} />
          <span className="input-group-btn">
            <a className="btn btn-default" onClick={addTodo}>Add</a>
          </span>
        </div>
        <ListView title="Todo List" items={todolist} panelClass="panel-primary" onClick={getDone} />
        <ListView title="Done List" items={donelist} panelClass="panel-success" labelClass="text-crossline" onClick={discard} />
      </div>
    )
  }
}

export default Todo;
